name: 'Make SBOM'
description: 'Make an SBOM via the REST API'
author: 'Colin Dembovsky'
branding:
  color: green
  icon: shield
inputs:
  token:
    required: false
    description: 'GitHub token with permissions to read SBOM'
    default: ${{ github.token }}
outputs:
  fileName:
    description: The filename of the SBOM makes
runs:
  using: 'node16'
  main: 'dist/index.js'
